### ISSUE TITLE
Your web server certificate is expired on mathmesh.com

### ISSUE THREAD

**Issue by stm-at-esd** [hallambaker/Mathematical-Mesh#3]
This page
http://mathmesh.com/Documents/draft-hallambaker-mesh-developer.html
is linked multiple times in the web.

Unfortunately the server certificate for mathmesh.com is expired.
It's a pity that there is no contact address for the web server on the page itself.

So I'm trying this way to transport my message to the recipient.

Best regards,
    Stefan

**Comment by hallambaker** [comment]
Thanks. Will see why certbot died.

**Comment by hallambaker** [comment]
Fixed
